refactor(dicts): urban dict
crimx/ext-saladict pull request #1513
Opened 2021-10-09 11:43 UTC by yipanhuasheng

fix #1501 
单个接口获取赞踩数，每日热词去除

2021-10-10 17:24 UTC, crimx requested changes

2021-10-10 17:24 UTC, crimx commented on src/components/dictionaries/urban/View.tsx
> +          {typeof def.thumbsUp === 'number' && (
这个修改是为了处理什么问题呢？

2021-10-10 17:24 UTC, crimx commented on src/components/dictionaries/urban/engine.ts
> +    .catch(handleNetWorkError)
点赞数属于次要信息，出现异常应该默默返回 null 就行。

2021-10-11 11:55 UTC, yipanhuasheng commented on src/components/dictionaries/urban/View.tsx
> +          {typeof def.thumbsUp === 'number' && (
react里边不转成布尔值，数字0会直接显示，就很怪

2021-10-11 11:56 UTC, yipanhuasheng commented on src/components/dictionaries/urban/engine.ts
> +    .catch(handleNetWorkError)
ok

2021-10-12 01:50 UTC, crimx commented on src/components/dictionaries/urban/View.tsx
> +          {typeof def.thumbsUp === 'number' && (
哦哦对，好哒

2021-10-12 01:52 UTC, crimx approved these changes

2021-10-12 01:52 UTC, merged